% This test file was generated by Copilot. Validate generated output before use.
classdef LeapYearTest < matlab.unittest.TestCase
    methods(Test)
        function testLeapYearDivisibleBy400(testCase)
            year = 2000;
            expected = true;

            actual = isLeapYear(year);

            testCase.verifyEqual(actual, expected);
        end

        function testLeapYearDivisibleBy4Not100(testCase)
            year = 2024;
            expected = true;

            actual = isLeapYear(year);

            testCase.verifyEqual(actual, expected);
        end

        function testNonLeapYearDivisibleBy100(testCase)
            year = 1900;
            expected = false;

            actual = isLeapYear(year);

            testCase.verifyEqual(actual, expected);
        end

        function testNonLeapYearNotDivisibleBy4(testCase)
            year = 2025;
            expected = false;

            actual = isLeapYear(year);

            testCase.verifyEqual(actual, expected);
        end
    end
end